<?php
header("Content-type: text/html; charset=utf-8"); 
if (isset($_GET['code'])) {
    try {
        $jos = \Jos\JosClient::getInstance();
        $token = $jos->fetchAccessToken($_GET['code']);
        Yaf\Session::getInstance()->token = $token;
        echo $context;
    } catch (JosApiException $e) {
        header('location:auth.php');
    }
} else {
    echo $context;
    $authUrl = \Jos\JosClient::getInstance()->getAuthUrl();
    echo <<<HTML
    <h1>
	<a href="{$authUrl}">点击去京东登录授权</a>
</h1>
HTML;
}
