<h1>
    <a href="{$this->authUrl}">点击去京东登录授权</a>
</h1>

<?php
if (isset($_GET['code'])) {
    try {
        $token = $this->fetchAccessToken($_GET['code'], $_GET['state']);
        \Yaf\Session::getInstance;//->set('token', $token);
        echo '<pre>';
        print_r($token);
    } catch (JosApiException $e) {
        header('location:auth.php');
    }
} else {
    $authUrl = $this->authUrl();
    echo <<<HTML
    <h1>
	<a href="{$authUrl}">点击去京东登录授权</a>
</h1>
    <p>默认回调地址是http://112.124.27.44:8080/yaf/public/index.php/rest/jingdong/auth</p>
HTML;
}
